name: Deploy WordPress Site

on:
  push:
    branches:
      - main      # Deploy when pushing to main
      - develop   # Deploy when pushing to develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH for Deployment
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Known Hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Rsync files to Server
        run: |
          rsync -avz --exclude='.git*' --exclude='node_modules' ./ root@159.223.211.112:/var/www/html
